<a href="https://colab.research.google.com/github/Simran-13/simran.18cse064/blob/main/DMDW_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Lab-2(Play with Dataset)

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
path="https://raw.githubusercontent.com/Anasuya-Sahoo/DMDW-Lab/main/Toyota.csv"
data=pd.read_csv(path)
data.head()

Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0           0  13500  23.0  46986  ...         0  2000  three    1165
1           1  13750  23.0  72937  ...         0  2000      3    1165
2           2  13950  24.0  41711  ...         0  2000      3    1165
3           3  14950  26.0  48000  ...         0  2000      3    1165
4           4  13750  30.0  38500  ...         0  2000      3    1170

[5 rows x 11 columns]

In [ ]:
data.dropna(axis=0,inplace=True)

In [ ]:
data.shape

(1111, 11)

In [ ]:
data.head()

Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0           0  13500  23.0  46986  ...         0  2000  three    1165
1           1  13750  23.0  72937  ...         0  2000      3    1165
3           3  14950  26.0  48000  ...         0  2000      3    1165
4           4  13750  30.0  38500  ...         0  2000      3    1170
5           5  12950  32.0  61000  ...         0  2000      3    1170

[5 rows x 11 columns]

In [ ]:
data.tail()


Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
1425        1425   7950  80.0     ??  ...         0  1300      4    1000
1429        1429   8950  78.0  24000  ...         1  1300      5    1065
1430        1430   8450  80.0  23000  ...         0  1300      3    1015
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[5 rows x 11 columns]

In [ ]:
import numpy as np
x = np.eye(5,dtype=int)
print("x =\n",x)

x =
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [ ]:
import numpy as np
a = [[1, 2], [3, 4]]
x = np.array(a)
print("list to array:\n",x)
a2 = x.tolist()
print("array to list:\n",a2)
print(a == a2)

list to array:
 [[1 2]
 [3 4]]
array to list:
 [[1, 2], [3, 4]]
True


In [ ]:
import numpy as np
N=int(input())# not more than N inputs will be considered
fvalues=list(map(float, input().split(' ')[:N]))
F = np.array(fvalues)
print("Values in Fahrenheit degrees:")
print(F)
print("Values in  Centigrade degrees:") 
print(5*F/9 - 5*32/9)

6
6
Values in Fahrenheit degrees:
[6.]
Values in  Centigrade degrees:
[-14.44444444]


In [ ]:
import numpy as np
from numpy import linalg as la  
R = int(input("Enter the number of rows:")) 
C = int(input("Enter the number of columns:"))   

if R==C:
  print("Enter the entries in a single line (separated by space): ") 
  entries = list(map(int, input().split()))   
  matrix = np.array(entries).reshape(R, C) 
  print("Original ",R,"x",C,"-D matrix")
  print(matrix)
  print("Determinant of the said ",R,"x",C,"-D matrix")
  print(np.linalg.det(matrix))
else:
  print("Invalid Dimensional Array Input")


Enter the number of rows:3
Enter the number of columns:3
Enter the entries in a single line (separated by space): 
3 1 2 4 5 6 7 8 9
Original  3 x 3 -D matrix
[[3 1 2]
 [4 5 6]
 [7 8 9]]
Determinant of the said  3 x 3 -D matrix
-8.999999999999998


In [ ]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.44609082 0.75355056 0.69880239 0.88323302 0.72163663]
 [0.93881224 0.71665689 0.8096066  0.52332143 0.51072513]
 [0.18100105 0.9698244  0.55355296 0.48410174 0.57202984]
 [0.06746262 0.89650479 0.77806308 0.71751204 0.77727344]
 [0.81803096 0.02796273 0.77841178 0.31892619 0.85771666]]
Minimum and Maximum Values:
0.027962727869807913 0.9698244049046427


In [ ]:
import numpy as np
x = np.array([[1,2,3], [4,5,6]])
print("Original array: ")
print(x)
print("Cumulative sum of the elements along a given axis:")
r = np.cumsum(x)
print(r)
print("\nSum over rows for each of the 3 columns:")
r = np.cumsum(x,axis=0) 
print(r)
print("\nSum over columns for each of the 2 rows:")
r = np.cumsum(x,axis=1) 
print(r)

Original array: 
[[1 2 3]
 [4 5 6]]
Cumulative sum of the elements along a given axis:
[ 1  3  6 10 15 21]

Sum over rows for each of the 3 columns:
[[1 2 3]
 [5 7 9]]

Sum over columns for each of the 2 rows:
[[ 1  3  6]
 [ 4  9 15]]


In [ ]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-11-22
Today:  2020-11-23
Tomorrow:  2020-11-24


In [ ]:
import numpy as np
x = np.array([' python exercises ', ' PHP  ', ' java  ', '  C++'], dtype=np.str)
print("Original Array:")
print(x)
stripped = np.char.strip(x)
print("\nRemove the leading and trailing whitespaces: ", stripped)

Original Array:
[' python exercises ' ' PHP  ' ' java  ' '  C++']

Remove the leading and trailing whitespaces:  ['python exercises' 'PHP' 'java' 'C++']


In [ ]:
import numpy as np
a=np.array([(1,2,3),(4,5,6)])
print(a)


[[1 2 3]
 [4 5 6]]


In [ ]:
import pandas as pd
data = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(data)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [ ]:
data

Unnamed: 0  Price   Age     KM  ... Automatic    CC  Doors  Weight
0              0  13500  23.0  46986  ...         0  2000  three    1165
1              1  13750  23.0  72937  ...         0  2000      3    1165
2              2  13950  24.0  41711  ...         0  2000      3    1165
3              3  14950  26.0  48000  ...         0  2000      3    1165
4              4  13750  30.0  38500  ...         0  2000      3    1170
...          ...    ...   ...    ...  ...       ...   ...    ...     ...
1431        1431   7500   NaN  20544  ...         0  1300      3    1025
1432        1432  10845  72.0     ??  ...         0  1300      3    1015
1433        1433   8500   NaN  17016  ...         0  1300      3    1015
1434        1434   7250  70.0     ??  ...         0  1300      3    1015
1435        1435   6950  76.0      1  ...         0  1600      5    1114

[1436 rows x 11 columns]

In [ ]:
import pandas as pd
s = pd.Series([2, 4, 6, 8, 10])
print(s)

0     2
1     4
2     6
3     8
4    10
dtype: int64


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [ ]:
import pandas as pd
import numpy as np
exam_data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]
df = pd.DataFrame(exam_data)
for index, row in df.iterrows():
    print(row['name'], row['score'])

Anastasia 12.5
Dima 9.0
Katherine 16.5


In [ ]:
import pandas as pd
df1 = pd.DataFrame({'A': [None, 0, None], 'B': [3, 4, 5]})
df2 = pd.DataFrame({'A': [1, 1, 3], 'B': [3, None, 3]})
df1.combine_first(df2)
print("Original DataFrames:")
print(df1)
print("--------------------")
print(df2)
print("\nMerge two dataframes with different columns:")
result = df1.combine_first(df2)
print(result)

Original DataFrames:
     A  B
0  NaN  3
1  0.0  4
2  NaN  5
--------------------
   A    B
0  1  3.0
1  1  NaN
2  3  3.0

Merge two dataframes with different columns:
     A  B
0  1.0  3
1  0.0  4
2  3.0  5


In [ ]:
import datetime
from datetime import datetime
print("Datetime object for Jan 11 2012:")
print(datetime(2012, 1, 11))
print("\nSpecific date and time of 9:20 pm") 
print(datetime(2011, 1, 11, 21, 20))
print("\nLocal date and time:")
print(datetime.now())
print("\nA date without time: ")
print(datetime.date(datetime(2012, 5, 22)))
print("\nCurrent date:")
print(datetime.now().date())
print("\nTime from a datetime:")
print(datetime.time(datetime(2012, 12, 15, 18, 12)))
print("\nCurrent local time:") 
print(datetime.now().time())

Datetime object for Jan 11 2012:
2012-01-11 00:00:00

Specific date and time of 9:20 pm
2011-01-11 21:20:00

Local date and time:
2020-11-23 05:45:16.130821

A date without time: 
2012-05-22

Current date:
2020-11-23

Time from a datetime:
18:12:00

Current local time:
05:45:16.131261


In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)
#pd.set_option('display.max_columns', None)
df = pd.DataFrame({
'ord_no':[70001,70009,70002,70004,70007,70005,70008,70010,70003,70012,70011,70013],
'purch_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'ord_date': ['2012-10-05','2012-09-10','2012-10-05','2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'customer_id':[3005,3001,3002,3009,3005,3007,3002,3004,3009,3008,3003,3002],
'salesman_id': [5002,5005,5001,5003,5002,5001,5001,5004,5003,5002,5004,5001]})
print("Original Orders DataFrame:")
print(df)
print("\nGroupby to find first order date for each group(salesman_id):")
result = df.groupby('salesman_id')['ord_date'].min()
print(result)

Original Orders DataFrame:
    ord_no  purch_amt    ord_date  customer_id  salesman_id
0    70001     150.50  2012-10-05         3005         5002
1    70009     270.65  2012-09-10         3001         5005
2    70002      65.26  2012-10-05         3002         5001
3    70004     110.50  2012-08-17         3009         5003
4    70007     948.50  2012-09-10         3005         5002
5    70005    2400.60  2012-07-27         3007         5001
6    70008    5760.00  2012-09-10         3002         5001
7    70010    1983.43  2012-10-10         3004         5004
8    70003    2480.40  2012-10-10         3009         5003
9    70012     250.45  2012-06-27         3008         5002
10   70011      75.29  2012-08-17         3003         5004
11   70013    3045.60  2012-04-25         3002         5001

Groupby to find first order date for each group(salesman_id):
salesman_id
5001    2012-04-25
5002    2012-06-27
5003    2012-08-17
5004    2012-08-17
5005    2012-09-10
Name: ord_date, dtype: 

In [ ]:
import pandas as pd
import numpy as np
np.random.seed(24)
df = pd.DataFrame({'A': np.linspace(1, 10, 10)})
df = pd.concat([df, pd.DataFrame(np.random.randn(10, 4), columns=list('BCDE'))],
               axis=1)
df.iloc[0, 2] = np.nan
df.iloc[3, 3] = np.nan
df.iloc[4, 1] = np.nan
df.iloc[9, 4] = np.nan
print("Original array:")
print(df)
print("\nBar charts in dataframe:")
df.style.bar(subset=['B', 'C'], color='#d65f5f')

Original array:
      A         B         C         D         E
0   1.0  1.329212       NaN -0.316280 -0.990810
1   2.0 -1.070816 -1.438713  0.564417  0.295722
2   3.0 -1.626404  0.219565  0.678805  1.889273
3   4.0  0.961538  0.104011       NaN  0.850229
4   5.0       NaN  1.057737  0.165562  0.515018
5   6.0 -1.336936  0.562861  1.392855 -0.063328
6   7.0  0.121668  1.207603 -0.002040  1.627796
7   8.0  0.354493  1.037528 -0.385684  0.519818
8   9.0  1.686583 -1.325963  1.428984 -2.089354
9  10.0 -0.129820  0.631523 -0.586538       NaN

Bar charts in dataframe:


In [ ]:
import pandas as pd
df = pd.DataFrame({
    'school_code': ['s001','s002','s003','s001','s002','s004'],
    'class': ['V', 'V', 'VI', 'VI', 'V', 'VI'],
    'name': ['Alberto Franco','Gino Mcneill','Ryan Parkes', 'Eesha Hinton', 'Gino Mcneill', 'David Parkes'],
    'date_of_birth': ['15/05/2002','17/05/2002','16/02/1999','25/09/1998','11/05/2002','15/09/1997'],
    'weight': [35, 37, 33, 30, 31, 32]})
     
print("Original DataFrame:")
print(df)
print("\nDefault Index Range:")
print(df.index)
df.index += 10 
print("\nNew Index Range:")
print(df.index)
print("\nDataFrame with new index:")
print(df)

Original DataFrame:
  school_code class            name date_of_birth  weight
0        s001     V  Alberto Franco    15/05/2002      35
1        s002     V    Gino Mcneill    17/05/2002      37
2        s003    VI     Ryan Parkes    16/02/1999      33
3        s001    VI    Eesha Hinton    25/09/1998      30
4        s002     V    Gino Mcneill    11/05/2002      31
5        s004    VI    David Parkes    15/09/1997      32

Default Index Range:
RangeIndex(start=0, stop=6, step=1)

New Index Range:
RangeIndex(start=10, stop=16, step=1)

DataFrame with new index:
   school_code class            name date_of_birth  weight
10        s001     V  Alberto Franco    15/05/2002      35
11        s002     V    Gino Mcneill    17/05/2002      37
12        s003    VI     Ryan Parkes    16/02/1999      33
13        s001    VI    Eesha Hinton    25/09/1998      30
14        s002     V    Gino Mcneill    11/05/2002      31
15        s004    VI    David Parkes    15/09/1997      32
